version: '3.8'
services:
  wendy-apiserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: wendy-apiserver:${IMAGE_TAG:-latest}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/dst/deply:/data/dst/deply  # 保持一致
    environment:
      - DEPLOYMENT_PATH=${DEPLOYMENT_PATH:-/data/dst/deply}
      - DATABASE_URL=${DATABASE_URL:-sqlite://data/wendy.sqlite3}
      - DOCKERFILE_PATH=${DOCKERFILE_PATH:-/app/template/Dockerfile.tar.xz}
    ports:
      - "8000:8000"
    restart: always
