services:
  wendy-apiserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: wendy-apiserver:${IMAGE_TAG:-latest}
    volumes:
      - ${PWD}/data:${PWD}/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEPLOYMENT_PATH=${PWD}/data
      - DATABASE_URL=sqlite:${PWD}/data/wendy.sqlite3
    ports:
      - "8000:8000"
    restart: always
