services:
  wendy-apiserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: wendy-apiserver:${IMAGE_TAG:-latest}
    volumes:
      - ${PWD}/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GAME_ARCHIVE_PATH=/data
      - DST_IMAGE=${DST_IMAGE:-swr.cn-north-4.myhuaweicloud.com/ylei/dontstarvetogether}
      - DATABASE_URL=sqlite:/data/wendy.sqlite3
    ports:
      - "8000:8000"
    restart: always


